[HDD]
	comment = HDD
	path = /mnt/HDD
	writable = yes
	public = yes
	valid users = pi www root
	write list = pi www root

[SSD]
	comment = SSD
	path = /mnt/SSD
	writable = yes
	public = yes
	valid users = pi www root
	write list = pi www root

[pi]
	comment = pi
	path = /home/pi
	writable = yes
	public = yes
	valid users = pi
	write list = pi
